<?php

namespace AppBundle\Repository;

/**
 * InstanceStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanceStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
