<?php

namespace AppBundle\Repository;

/**
 * LockFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LockFileRepository extends \Doctrine\ORM\EntityRepository
{
}
