<?php

namespace AppBundle\Repository;

/**
 * LogNotifyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogNotifyRepository extends \Doctrine\ORM\EntityRepository
{
}
