<?php

namespace AppBundle\Repository;

/**
 * URLRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class URLRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUrlsByInstance($instance, $visible = 1)
    {
        return $this->createQueryBuilder('u')
            ->select('u.url,u.host,u.title as msg')
            ->join('u.instance', 'i')
            ->where('i = :instance')
            ->andWhere('u.active = :visible')
            ->setParameter("instance", $instance)
            ->setParameter("visible", $visible)
            ->getQuery()
            ->getResult();

    }

//    public function getUrlsBackendByInstance($instance, ?$env, $visible = 1)
//    {
//        return $this->createQueryBuilder('u')
//            ->select('u.url,u.host,u.title as msg')
//            ->join('u.instance', 'i')
//            ->where('i = :instance')
//            ->andWhere('u.active = :visible')
//            ->setParameter("instance", $instance)
//            ->setParameter("visible", $visible)
//            ->getQuery()
//            ->getResult();
//
//    }
}
