aws:
    version: latest
    region: eu-west-1
    credentials:
        key: ******************
        secret: '*********************'
#    ec2:
#        region: 'eu-west-1'
#        version: '2016-11-15'
    S3:
        version: '2006-03-01'
