app:
    resource: "@AppBundle/Controller/"
    type:     annotation
  
#FOS USER
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"